Feature align doc fields
alipay/global-open-sdk-java pull request #33
Opened 2024-07-30 03:15 UTC by wangzunjiao

2024-07-30 10:17 UTC, ScottWryyyyy requested changes

2024-07-30 10:17 UTC, ScottWryyyyy commented on src/main/java/com/alipay/global/api/request/ams/pay/AlipayPayRequest.java
> +    private ExtendInfo              extendInfo;
这个是为啥需要改类型

2024-07-30 10:17 UTC, ScottWryyyyy commented on src/main/java/com/alipay/global/api/request/ams/pay/AlipayRefundRequest.java
> +
refundDetails和refundSourceAccountNo这两个字段是从哪里获取的

2024-07-31 08:22 UTC, wangzunjiao commented on src/main/java/com/alipay/global/api/request/ams/pay/AlipayPayConsultRequest.java
> +     *
对的，这里的变量类型是String，注释里表明可以用MerchantRegionType.*.name 枚举方式

2024-08-02 02:49 UTC, merged